apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adt-auth.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
    spring.datasource.url: "jdbc:postgresql://alpha-pg.postgres.database.azure.com:5432/hrms_sit?prepareThreshold=0"
    spring.datasource.username: AlphaUser
    spring.datasource.password: User@123$
    app.jwt.secret: A59C2D88BB4BA3BFB54567928A796
  